name: "ShellCheck"

on:
  push:
    branches: [master]
    paths:
      - update-cf-ip.sh
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Shellcheck
        run: shellcheck update-cf-ip.sh
